apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-config-config
  labels:
    app: cloud-config
data:
  SPRING_PROFILES_ACTIVE: "docker"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka"
