apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  labels:
    app: product-service
data:
  SPRING_PROFILES_ACTIVE: "docker"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka"
