apiVersion: v1
kind: ConfigMap
metadata:
  name: service-discovery-config
  labels:
    app: service-discovery
data:
  SPRING_PROFILES_ACTIVE: "docker"
  EUREKA_INSTANCE_HOSTNAME: "service-discovery"
