apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-discovery/deployment.yaml
  - service-discovery/service.yaml
  - service-discovery/configmap.yaml
  - cloud-config/deployment.yaml
  - cloud-config/service.yaml
  - cloud-config/configmap.yaml
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - api-gateway/configmap.yaml
  - user-service/deployment.yaml
  - user-service/service.yaml
  - user-service/configmap.yaml
  - product-service/deployment.yaml
  - product-service/service.yaml
  - product-service/configmap.yaml
  - order-service/deployment.yaml
  - order-service/service.yaml
  - order-service/configmap.yaml
  - payment-service/deployment.yaml
  - payment-service/service.yaml
  - payment-service/configmap.yaml
  - shipping-service/deployment.yaml
  - shipping-service/service.yaml
  - shipping-service/configmap.yaml
  - favourite-service/deployment.yaml
  - favourite-service/service.yaml
  - favourite-service/configmap.yaml

labels:
  - pairs:
      project: ecommerce-microservices
    includeSelectors: true
